/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as OtherRouteImport } from './routes/other'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundsRouteImport } from './routes/legal/refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalPricingRouteImport } from './routes/legal/pricing'
import { Route as LegalAcknowledgementsRouteImport } from './routes/legal/acknowledgements'
import { Route as LegalAboutRouteImport } from './routes/legal/about'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthUsersRouteImport } from './routes/auth/users'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSetNewPasswordRouteImport } from './routes/auth/setNewPassword'
import { Route as AuthRequestPasswordResetRouteImport } from './routes/auth/requestPasswordReset'
import { Route as AuthProfileRouteImport } from './routes/auth/profile'
import { Route as AuthForRouteTroubleshootingRouteImport } from './routes/auth/forRouteTroubleshooting'
import { Route as AuthCreditsRouteImport } from './routes/auth/credits'
import { ServerRoute as ApiTestEnvServerRouteImport } from './routes/api/test-env'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const OtherRoute = OtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPricingRoute = LegalPricingRouteImport.update({
  id: '/legal/pricing',
  path: '/legal/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcknowledgementsRoute = LegalAcknowledgementsRouteImport.update({
  id: '/legal/acknowledgements',
  path: '/legal/acknowledgements',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAboutRoute = LegalAboutRouteImport.update({
  id: '/legal/about',
  path: '/legal/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/auth/users',
  path: '/auth/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetNewPasswordRoute = AuthSetNewPasswordRouteImport.update({
  id: '/auth/setNewPassword',
  path: '/auth/setNewPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequestPasswordResetRoute =
  AuthRequestPasswordResetRouteImport.update({
    id: '/auth/requestPasswordReset',
    path: '/auth/requestPasswordReset',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForRouteTroubleshootingRoute =
  AuthForRouteTroubleshootingRouteImport.update({
    id: '/auth/forRouteTroubleshooting',
    path: '/auth/forRouteTroubleshooting',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCreditsRoute = AuthCreditsRouteImport.update({
  id: '/auth/credits',
  path: '/auth/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEnvServerRoute = ApiTestEnvServerRouteImport.update({
  id: '/api/test-env',
  path: '/api/test-env',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/other': typeof OtherRoute
  '/auth/credits': typeof AuthCreditsRoute
  '/auth/forRouteTroubleshooting': typeof AuthForRouteTroubleshootingRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/requestPasswordReset': typeof AuthRequestPasswordResetRoute
  '/auth/setNewPassword': typeof AuthSetNewPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/users': typeof AuthUsersRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/acknowledgements': typeof LegalAcknowledgementsRoute
  '/legal/pricing': typeof LegalPricingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/other': typeof OtherRoute
  '/auth/credits': typeof AuthCreditsRoute
  '/auth/forRouteTroubleshooting': typeof AuthForRouteTroubleshootingRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/requestPasswordReset': typeof AuthRequestPasswordResetRoute
  '/auth/setNewPassword': typeof AuthSetNewPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/users': typeof AuthUsersRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/acknowledgements': typeof LegalAcknowledgementsRoute
  '/legal/pricing': typeof LegalPricingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/other': typeof OtherRoute
  '/auth/credits': typeof AuthCreditsRoute
  '/auth/forRouteTroubleshooting': typeof AuthForRouteTroubleshootingRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/requestPasswordReset': typeof AuthRequestPasswordResetRoute
  '/auth/setNewPassword': typeof AuthSetNewPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/users': typeof AuthUsersRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/acknowledgements': typeof LegalAcknowledgementsRoute
  '/legal/pricing': typeof LegalPricingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/other'
    | '/auth/credits'
    | '/auth/forRouteTroubleshooting'
    | '/auth/profile'
    | '/auth/requestPasswordReset'
    | '/auth/setNewPassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/users'
    | '/auth/verify-email'
    | '/legal/about'
    | '/legal/acknowledgements'
    | '/legal/pricing'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/other'
    | '/auth/credits'
    | '/auth/forRouteTroubleshooting'
    | '/auth/profile'
    | '/auth/requestPasswordReset'
    | '/auth/setNewPassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/users'
    | '/auth/verify-email'
    | '/legal/about'
    | '/legal/acknowledgements'
    | '/legal/pricing'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/other'
    | '/auth/credits'
    | '/auth/forRouteTroubleshooting'
    | '/auth/profile'
    | '/auth/requestPasswordReset'
    | '/auth/setNewPassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/users'
    | '/auth/verify-email'
    | '/legal/about'
    | '/legal/acknowledgements'
    | '/legal/pricing'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  OtherRoute: typeof OtherRoute
  AuthCreditsRoute: typeof AuthCreditsRoute
  AuthForRouteTroubleshootingRoute: typeof AuthForRouteTroubleshootingRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthRequestPasswordResetRoute: typeof AuthRequestPasswordResetRoute
  AuthSetNewPasswordRoute: typeof AuthSetNewPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  LegalAboutRoute: typeof LegalAboutRoute
  LegalAcknowledgementsRoute: typeof LegalAcknowledgementsRoute
  LegalPricingRoute: typeof LegalPricingRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
}
export interface FileServerRoutesByFullPath {
  '/api/test-env': typeof ApiTestEnvServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/test-env': typeof ApiTestEnvServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/test-env': typeof ApiTestEnvServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/test-env' | '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/test-env' | '/api/auth/$'
  id: '__root__' | '/api/test-env' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiTestEnvServerRoute: typeof ApiTestEnvServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/other': {
      id: '/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof OtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/pricing': {
      id: '/legal/pricing'
      path: '/legal/pricing'
      fullPath: '/legal/pricing'
      preLoaderRoute: typeof LegalPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acknowledgements': {
      id: '/legal/acknowledgements'
      path: '/legal/acknowledgements'
      fullPath: '/legal/acknowledgements'
      preLoaderRoute: typeof LegalAcknowledgementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/about': {
      id: '/legal/about'
      path: '/legal/about'
      fullPath: '/legal/about'
      preLoaderRoute: typeof LegalAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/users': {
      id: '/auth/users'
      path: '/auth/users'
      fullPath: '/auth/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setNewPassword': {
      id: '/auth/setNewPassword'
      path: '/auth/setNewPassword'
      fullPath: '/auth/setNewPassword'
      preLoaderRoute: typeof AuthSetNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/requestPasswordReset': {
      id: '/auth/requestPasswordReset'
      path: '/auth/requestPasswordReset'
      fullPath: '/auth/requestPasswordReset'
      preLoaderRoute: typeof AuthRequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forRouteTroubleshooting': {
      id: '/auth/forRouteTroubleshooting'
      path: '/auth/forRouteTroubleshooting'
      fullPath: '/auth/forRouteTroubleshooting'
      preLoaderRoute: typeof AuthForRouteTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/credits': {
      id: '/auth/credits'
      path: '/auth/credits'
      fullPath: '/auth/credits'
      preLoaderRoute: typeof AuthCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/test-env': {
      id: '/api/test-env'
      path: '/api/test-env'
      fullPath: '/api/test-env'
      preLoaderRoute: typeof ApiTestEnvServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  OtherRoute: OtherRoute,
  AuthCreditsRoute: AuthCreditsRoute,
  AuthForRouteTroubleshootingRoute: AuthForRouteTroubleshootingRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRequestPasswordResetRoute: AuthRequestPasswordResetRoute,
  AuthSetNewPasswordRoute: AuthSetNewPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  LegalAboutRoute: LegalAboutRoute,
  LegalAcknowledgementsRoute: LegalAcknowledgementsRoute,
  LegalPricingRoute: LegalPricingRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiTestEnvServerRoute: ApiTestEnvServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
