/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotPagesAboutRouteImport } from './pages/about'
import { Route as DotIndexRouteImport } from './routes/index'

const DotDotPagesAboutRoute = DotDotPagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DotIndexRoute = DotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DotIndexRoute
  '/about': typeof DotDotPagesAboutRoute
}
export interface FileRoutesByTo {
  '/': typeof DotIndexRoute
  '/about': typeof DotDotPagesAboutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof DotIndexRoute
  '/about': typeof DotDotPagesAboutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about'
  id: '__root__' | '/' | '/about'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotIndexRoute: typeof DotIndexRoute
  DotDotPagesAboutRoute: typeof DotDotPagesAboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DotDotPagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DotIndexRoute: DotIndexRoute,
  DotDotPagesAboutRoute: DotDotPagesAboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
